### ISSUE TITLE
想问几个问题

### ISSUE THREAD

**Issue by s4028600** [savvym/pydmzj#1]
这有办法抓dm5的吗
有办法将打印结果输出到txt档吗

**Comment by s4028600** [comment]
试着改
变成这样

#遍历漫画

import urllib.request
import json
import jsonpath
import os

#获取json的函数：
def get_record(url):
    resp = urllib.request.urlopen(url)
    ele_json = json.loads(resp.read())
    return ele_json

if __name__ == '__main__':
    a = int(input("输入一个漫画id下限："))
    x = a
    b = int(input("输入一个漫画id上限: "))
    while x <= b :
        url = 'http://v2.api.dmzj.com/comic/%d.json' % (x)
        id = jsonpath.jsonpath(get_record(url),'$.id')
        if(id == False):
            x += 1
        else:
            print('id:', id)
            title = jsonpath.jsonpath(get_record(url),'$.title')
            print('name:', title)
        #print(get_record(url))
            x += 1
            for t in title:
                f = open('ID.txt','a',encoding="utf-8-sig")
                f.write(t+'\n')
                f.close()
os.system("pause")

打印1~10
txt会这样
blood+
光速蒙面侠21

但是理想是
8
blood+
10
光速蒙面侠21

或
8 blood+
10 光速蒙面侠21

那个ID不知道要怎么用

**Comment by savvym** [comment]
要想打印到txt文件的话，在print函数里直接将结果打印到文件就好了。
def get_record(url):
    resp = urllib.request.urlopen(url)
    ele_json = json.loads(resp.read())
    return ele_json

if __name__ == '__main__':
    a = int(input("输入一个小说id下限："))
    x = a
    b = int(input("输入一个小说id上限: "))
    **f = open('test.txt','w')**

    while x <= b :
        url = 'http://v2.api.dmzj.com/novel/%d.json' % (x)
        id = jsonpath.jsonpath(get_record(url),'$.id')
        if(id == False):
            x += 1
        else:
            print('id:', id,**file=f**)
            name = jsonpath.jsonpath(get_record(url),'$.name')
            print('name:', name,**file = f**)
            x += 1
    **f.close()**

**Comment by savvym** [comment]
想把结果输出到txt的话在print函数直接写到文件就好了,在循环外打开文件，print写入文件，然后关闭文件。
```
def get_record(url):
    resp = urllib.request.urlopen(url)
    ele_json = json.loads(resp.read())
    return ele_json

if __name__ == '__main__':
    a = int(input("输入一个小说id下限："))
    x = a
    b = int(input("输入一个小说id上限: "))

    f = open('test.txt','w')  //test.txt
    
while x <= b :
        url = 'http://v2.api.dmzj.com/novel/%d.json' % (x)
        id = jsonpath.jsonpath(get_record(url),'$.id')
        if(id == False):
            x += 1
        else:
            print('id:', id,file=f) /  /将id写入test.txt
            name = jsonpath.jsonpath(get_record(url),'$.name')
            print('name:', name,file = f)   //将name写入test.txt
            x += 1
    f.close() //关闭文件
```

**Comment by s4028600** [comment]
以为写入TXT一定要放在代码后面
居然还可以这样写
虽然会跑出两个中括号这样
[8] ['blood+']
不过感谢提供思路

好像没有DM5和1kkk的API
不然我也想爬着这个网站的ID

**Comment by s4028600** [comment]
我把他稍微改造之后变这样
```
import urllib.request
import json
import jsonpath
import os
import random,time

def get_record(url):
    resp = urllib.request.urlopen(url)
    ele_json = json.loads(resp.read())
    return ele_json

if __name__ == '__main__':
    a = int(input("输入一个漫画id下限："))
    x = a
    b = int(input("输入一个漫画id上限: "))

    while x <= b :
        f = open('ID.txt','a',encoding="utf-8-sig")
        url = 'http://v2.api.dmzj.com/comic/%d.json' % (x)
        id = jsonpath.jsonpath(get_record(url),'$.id')
        if(id == False):
            x += 1
        else:
            print(id)
            title = jsonpath.jsonpath(get_record(url),'$.title')
            print(id[0],'\t',title[0],file=f)
            time.sleep(random.randint(1,5))
        #print(get_record(url))
            x += 1
    f.close()
```
把打开文件移到while下是因为会突然错误跑出这个
```
Traceback (most recent call last):
  File "D:\long\Desktop\pydmzj\ComicID.py", line 23, in <module>
    id = jsonpath.jsonpath(get_record(url),'$.id')
  File "D:\long\Desktop\pydmzj\ComicID.py", line 11, in get_record
    resp = urllib.request.urlopen(url)
  File "C:\Users\long\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\long\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\long\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\long\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\long\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\long\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
```
根据翻译应该是连线断了
也试过用延迟时间
但还是会断...

**Comment by savvym** [comment]
我挂vpn的时候出现过这个连接问题，关掉就没问题了。

**Comment by s4028600** [comment]
实验了老半天
决定放弃socket.setdefaulttimeout
改成
```
import urllib.request
import json
import jsonpath
import os
import random,time

def get_record(url):
    resp = urllib.request.urlopen(url)
    ele_json = json.loads(resp.read())
    return ele_json

if __name__ == '__main__':
    a = int(input("输入一个漫画id下限："))
    x = a
    b = int(input("输入一个漫画id上限: "))

    f = open('ID.txt','a',encoding="utf-8-sig")

    while x <= b :
     for i in range(1):
      try:
        url = 'http://v2.api.dmzj.com/comic/%d.json' % (x)
        id = jsonpath.jsonpath(get_record(url),'$.id')
        time.sleep(random.randint(1,5))
        if(id == False):
            x += 1
        else:
            print(id)
            title = jsonpath.jsonpath(get_record(url),'$.title')
            print(id[0],'\t',title[0],file=f)
        #print(get_record(url))
            x += 1
      except:
            time.sleep(10)
f.close()
```
虽然爬很慢...


試著讀取作者
jsonpath.jsonpath(get_record(url),'$.authors')
会跑出
[[{'tag_id': 887, 'tag_name': '桂明日香'}]]
有办法只读取tag_name吗

**Comment by savvym** [comment]
观察可以看出来tag_name在四个不同的类别下都有，先提取出来tag_name的列表，因为是嵌套，所以用'$..tag_name'两个点
```
tag_name = jsonpath.jsonpath(get_record(url),'$..tag_name')
```
此时你print(tag_name)是一个列表:
```
['冒险', '热血', '高清单行', '桂明日香', '已完结']
```
那么你只要取第4项就可以了，print('tag_name:', tag_name[3])，就会出现只有一个结果：
```
tag_name: 桂明日香
```

**Comment by savvym** [comment]
我更新了一下ComicID.py文件，改用字典操作来处理json数据，json数据通过python处理之后类型就成了字典和列表相互嵌套的类型了，根据需要该用字典查的查，该用列表定位的定位，基本所有东西就都能找到了。

**Comment by s4028600** [comment]
现在电脑不在不能测试
Jsonpath里有
id为真时执行else
dict没有这条的原理是？

顺道一提
```
观察可以看出来tag_name在四个不同的类别下都有，先提取出来tag_name的列表，因为是嵌套，所以用'$..tag_name'两个点
以下略
```
这种我才看比较的懂...
你给的使用教程对我这菜鸟有点难理解甚至看不懂...
感谢两样都提供来比对


dict...
又是没看过的代码模式了...

**Comment by savvym** [comment]
其实就是处理数据的不同结构，dict也是比较基本的python数据类型，可以看一下相关教程[Python3 字典](https://www.runoob.com/python3/python3-dictionary.html)

**Comment by s4028600** [comment]
了解
会再研究
问题目前应该差不多了

**Comment by s4028600** [comment]
start = time.process_time()
这条指令是要做什么
